"""The one place that knows whether the app's own data lives in SQLite or PostgreSQL.

Set `DATABASE_URL` and the app stores everything in PostgreSQL; leave it unset and it
uses the SQLite file under `DATA_DIR`, exactly as it always has. Local development
needs no database server, and a deployment that has no writable disk â€” anything
serverless â€” gets storage that actually survives a restart.

Everything else in the app keeps writing SQLite-flavoured SQL with `?` placeholders.
This module translates at the boundary:

* `connect()` returns an object with sqlite3's small surface (`execute`, `executemany`,
  `commit`, `close`, `cursor`) whichever backend is in use, and rows that support both
  `row["name"]` and `row[0]` â€” psycopg2's DictCursor matches sqlite3.Row there, which is
  why it's used in preference to RealDictCursor.
* `?` becomes `%s` on the way to PostgreSQL.
* The handful of statements that genuinely can't be shared â€” identity columns, getting
  the id of an inserted row, date arithmetic â€” are exposed here as dialect constants
  rather than being branched on at each call site.
"""

import os
import re
import sqlite3

from query_assistant.config import DB_PATH

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
IS_POSTGRES = bool(DATABASE_URL)

DIALECT = "PostgreSQL" if IS_POSTGRES else "SQLite"

QUOTE = chr(34)

# An auto-incrementing primary key.
IDENTITY_PK = (
    "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    if IS_POSTGRES
    else "id INTEGER PRIMARY KEY AUTOINCREMENT"
)

# Filters over `orders.order_date`, which is a TEXT column in SQLite and a DATE in
# PostgreSQL. Written once here so rule_engine doesn't have to care.
DATE_FILTERS = {
    "today": (
        "o.order_date::date = CURRENT_DATE"
        if IS_POSTGRES
        else "DATE(o.order_date) = DATE('now')"
    ),
    "this_month": (
        "date_trunc('month', o.order_date::date) = date_trunc('month', CURRENT_DATE)"
        if IS_POSTGRES
        else "strftime('%Y-%m', o.order_date) = strftime('%Y-%m', 'now')"
    ),
    "last_month": (
        "date_trunc('month', o.order_date::date) "
        "= date_trunc('month', CURRENT_DATE - INTERVAL '1 month')"
        if IS_POSTGRES
        else "strftime('%Y-%m', o.order_date) = strftime('%Y-%m', 'now', '-1 month')"
    ),
    "this_year": (
        "date_trunc('year', o.order_date::date) = date_trunc('year', CURRENT_DATE)"
        if IS_POSTGRES
        else "strftime('%Y', o.order_date) = strftime('%Y', 'now')"
    ),
}

# Only rewrites placeholders that stand alone. A `?` inside a quoted string would be
# data, not a parameter marker, and must be left as it is.
_PLACEHOLDER_PATTERN = re.compile(r"\?(?=(?:[^']*'[^']*')*[^']*$)")


def quote_ident(name):
    """Quote a schema-supplied identifier for interpolation into SQL.

    Table and column names can't be bound as parameters, so they get interpolated
    â€” and a name is not automatically safe just because it came from a database's
    own catalogue, since the database itself may be one a visitor attached. Both
    SQLite and PostgreSQL allow a double quote inside an identifier, which would
    otherwise close the quoting early and let the rest of the name be read as SQL.
    Doubling the quote is the escape both engines define, so one function covers
    every caller.
    """
    return QUOTE + name.replace(QUOTE, QUOTE * 2) + QUOTE


def to_dialect(sql):
    """Rewrite SQLite-flavoured SQL for the backend actually in use."""
    if not IS_POSTGRES:
        return sql
    return _PLACEHOLDER_PATTERN.sub("%s", sql)


class _PostgresCursor:
    """psycopg2's cursor, with the two conveniences sqlite3's callers expect."""

    def __init__(self, cursor):
        self._cursor = cursor

    def execute(self, sql, params=()):
        self._cursor.execute(to_dialect(sql), tuple(params))
        return self

    def executemany(self, sql, seq):
        self._cursor.executemany(to_dialect(sql), [tuple(p) for p in seq])
        return self

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    def close(self):
        self._cursor.close()

    @property
    def description(self):
        return self._cursor.description


class _PostgresConnection:
    """A psycopg2 connection wearing sqlite3.Connection's interface.

    sqlite3 lets you call `execute` on the connection directly and most of this app
    does; psycopg2 requires a cursor. Bridging it here means no call site has to know
    which database it's talking to.
    """

    def __init__(self, connection):
        self._connection = connection

    def execute(self, sql, params=()):
        return _PostgresCursor(self._connection.cursor()).execute(sql, params)

    def executemany(self, sql, seq):
        return _PostgresCursor(self._connection.cursor()).executemany(sql, seq)

    def cursor(self):
        return _PostgresCursor(self._connection.cursor())

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()


def connect(db_path=None):
    """Open a connection to the app's own database.

    `db_path` overrides the SQLite file (the test suite points it at a temp file) and
    is ignored when DATABASE_URL is set, since there's no file involved then.
    """
    if IS_POSTGRES:
        import psycopg2
        import psycopg2.extras

        # DictCursor, not RealDictCursor: its rows support both row["name"] and row[0],
        # which is what sqlite3.Row does and what this app's callers assume.
        connection = psycopg2.connect(
            DATABASE_URL, cursor_factory=psycopg2.extras.DictCursor, connect_timeout=10
        )
        return _PostgresConnection(connection)

    connection = sqlite3.connect(db_path or DB_PATH)
    connection.row_factory = sqlite3.Row
    return connection


def insert_returning_id(conn, sql, params):
    """Run an INSERT and return the new row's id.

    SQLite exposes it as `lastrowid` after the fact; PostgreSQL needs to be asked for
    it as part of the statement.
    """
    if IS_POSTGRES:
        return conn.execute(sql + " RETURNING id", params).fetchone()[0]
    return conn.execute(sql, params).lastrowid
